# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bb8fb86cdc4cbf2c9573b8c6ef4efe5264be1ef53eca5c0065894696cfaad572bd94b7804116c82c074a757687f609adfd8b735b8820db53083927341ee2a92

test:
  secret_key_base: 309fa027a04653acec92feac676972a2eb3602559e74edd78d9aa7e843ef60f1c98ba137470105ea62bf5058f3a16449129c4b0228f7efc45c46dfdc2ffe00a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
